# Generated by Django 6.0.4 on 2026-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneno', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
