# Generated by Django 6.0.4 on 2026-04-29 09:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contact_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='AU', unique=True),
        ),
    ]
