# Generated by Django 6.0.4 on 2026-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_contact_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
